services:
  load_balancer:
    image: golift:latest
    ports:
      - "8080:8080"
    environment:
      NUM_OF_SERVERS: "5"
      STARTING_PORT: "8000"
      LOAD_BALANCER_PORT: "8080"
    command: ["./main"]
