version: '3.8'

services:
  load_balancer:
    build:
      context: .  # Use current directory as build context
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NUM_OF_SERVERS: "5"
      STARTING_PORT: "8000"
      LOAD_BALANCER_PORT: "8080"
      API_HOST: "127.0.0.1"


